version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /
      - /packages/mineflayer-ui
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-major"
    groups:
      prismarine:
        applies-to: version-updates
        patterns:
          - "mineflayer*"
          - "minecraft-data"
          - "prismarine-*"
          - "protodef*"
          - "vec3"
        update-types:
          - minor
          - patch
      npm-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "mineflayer*"
          - "minecraft-data"
          - "prismarine-*"
          - "protodef*"
          - "vec3"
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
